<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\Provider;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Acetaminofén 500mg',
                'description' => 'Tabletas para el alivio del dolor y la fiebre.',
                'price' => 3500,
                'stock' => 120,
                'code' => 'ACETA500',
                'image' => null,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'provider_id' => Provider::where('name', 'Laboratorios Genéricos S.A.S.')->first()->id,
            ],
            [
                'name' => 'Ibuprofeno 400mg',
                'description' => 'Antiinflamatorio y analgésico.',
                'price' => 4200,
                'stock' => 80,
                'code' => 'IBU400',
                'image' => null,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'provider_id' => Provider::where('name', 'Distribuidora FarmaPlus')->first()->id,
            ],
            [
                'name' => 'Multivitamínico Complejo B',
                'description' => 'Suplemento vitamínico para adultos.',
                'price' => 15000,
                'stock' => 50,
                'code' => 'MULTIB',
                'image' => null,
                'category_id' => Category::where('name', 'Vitaminas y suplementos')->first()->id,
                'provider_id' => Provider::where('name', 'Salud y Vida Ltda.')->first()->id,
            ],
            [
                'name' => 'Jabón antibacterial',
                'description' => 'Jabón líquido para manos.',
                'price' => 7000,
                'stock' => 60,
                'code' => 'JABANTIB',
                'image' => null,
                'category_id' => Category::where('name', 'Higiene')->first()->id,
                'provider_id' => Provider::where('name', 'Farmacéutica Andina')->first()->id,
            ],
            [
                'name' => 'Termómetro digital',
                'description' => 'Termómetro de uso oral y axilar.',
                'price' => 25000,
                'stock' => 30,
                'code' => 'TERMODIG',
                'image' => null,
                'category_id' => Category::where('name', 'Dispositivos médicos')->first()->id,
                'provider_id' => Provider::where('name', 'Distribuidora FarmaPlus')->first()->id,
            ],
            [
                'name' => 'Alcohol antiséptico 70%',
                'description' => 'Solución desinfectante para uso externo.',
                'price' => 5500,
                'stock' => 100,
                'code' => 'ALCOHOL70',
                'image' => null,
                'category_id' => Category::where('name', 'Higiene')->first()->id,
                'provider_id' => Provider::where('name', 'Laboratorios Genéricos S.A.S.')->first()->id,
            ],
            [
                'name' => 'Vitamina C 1000mg',
                'description' => 'Tabletas efervescentes para fortalecer el sistema inmune.',
                'price' => 12000,
                'stock' => 40,
                'code' => 'VITC1000',
                'image' => null,
                'category_id' => Category::where('name', 'Vitaminas y suplementos')->first()->id,
                'provider_id' => Provider::where('name', 'Salud y Vida Ltda.')->first()->id,
            ],
            [
                'name' => 'Gasa estéril 10x10cm',
                'description' => 'Paquete de gasas estériles para curaciones.',
                'price' => 3500,
                'stock' => 200,
                'code' => 'GASA10X10',
                'image' => null,
                'category_id' => Category::where('name', 'Dispositivos médicos')->first()->id,
                'provider_id' => Provider::where('name', 'Farmacéutica Andina')->first()->id,
            ],
            [
                'name' => 'Crema dental fluor',
                'description' => 'Crema dental con flúor para protección anticaries.',
                'price' => 6500,
                'stock' => 90,
                'code' => 'CREMADENT',
                'image' => null,
                'category_id' => Category::where('name', 'Higiene')->first()->id,
                'provider_id' => Provider::where('name', 'Distribuidora FarmaPlus')->first()->id,
            ],
            [
                'name' => 'Enjuague bucal menta',
                'description' => 'Enjuague bucal refrescante sabor menta.',
                'price' => 8000,
                'stock' => 70,
                'code' => 'ENJBUCAL',
                'image' => null,
                'category_id' => Category::where('name', 'Higiene')->first()->id,
                'provider_id' => Provider::where('name', 'Farmacéutica Andina')->first()->id,
            ],
            [
                'name' => 'Paracetamol 500mg',
                'description' => 'Analgésico y antipirético.',
                'price' => 3400,
                'stock' => 110,
                'code' => 'PARAC500',
                'image' => null,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'provider_id' => Provider::where('name', 'Laboratorios Genéricos S.A.S.')->first()->id,
            ],
            [
                'name' => 'Omeprazol 20mg',
                'description' => 'Cápsulas para el tratamiento de la acidez estomacal.',
                'price' => 9800,
                'stock' => 60,
                'code' => 'OME20',
                'image' => null,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'provider_id' => Provider::where('name', 'Salud y Vida Ltda.')->first()->id,
            ],
            [
                'name' => 'Suero oral sabor naranja',
                'description' => 'Solución oral para hidratación.',
                'price' => 4500,
                'stock' => 75,
                'code' => 'SUERONAR',
                'image' => null,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'provider_id' => Provider::where('name', 'Distribuidora FarmaPlus')->first()->id,
            ],
            [
                'name' => 'Toallas húmedas',
                'description' => 'Paquete de toallas húmedas para higiene personal.',
                'price' => 6000,
                'stock' => 130,
                'code' => 'TOALLHUM',
                'image' => null,
                'category_id' => Category::where('name', 'Cuidado personal')->first()->id,
                'provider_id' => Provider::where('name', 'Farmacéutica Andina')->first()->id,
            ],
            [
                'name' => 'Protector solar SPF 50',
                'description' => 'Protección solar alta para todo tipo de piel.',
                'price' => 32000,
                'stock' => 25,
                'code' => 'PROTSOL50',
                'image' => null,
                'category_id' => Category::where('name', 'Cuidado personal')->first()->id,
                'provider_id' => Provider::where('name', 'Salud y Vida Ltda.')->first()->id,
            ],
            [
                'name' => 'Tensiometro digital',
                'description' => 'Medidor de presión arterial digital.',
                'price' => 85000,
                'stock' => 10,
                'code' => 'TENSIODIG',
                'image' => null,
                'category_id' => Category::where('name', 'Dispositivos médicos')->first()->id,
                'provider_id' => Provider::where('name', 'Laboratorios Genéricos S.A.S.')->first()->id,
            ],
            [
                'name' => 'Shampoo anticaspa',
                'description' => 'Shampoo para el control de la caspa.',
                'price' => 12000,
                'stock' => 55,
                'code' => 'SHAMPANT',
                'image' => null,
                'category_id' => Category::where('name', 'Cuidado personal')->first()->id,
                'provider_id' => Provider::where('name', 'Distribuidora FarmaPlus')->first()->id,
            ],
            [
                'name' => 'Algodón absorbente',
                'description' => 'Bolsita de algodón para curaciones.',
                'price' => 2500,
                'stock' => 180,
                'code' => 'ALGODON',
                'image' => null,
                'category_id' => Category::where('name', 'Dispositivos médicos')->first()->id,
                'provider_id' => Provider::where('name', 'Farmacéutica Andina')->first()->id,
            ],
            [
                'name' => 'Vitamina D 2000UI',
                'description' => 'Suplemento de vitamina D para adultos.',
                'price' => 18000,
                'stock' => 35,
                'code' => 'VITD2000',
                'image' => null,
                'category_id' => Category::where('name', 'Vitaminas y suplementos')->first()->id,
                'provider_id' => Provider::where('name', 'Salud y Vida Ltda.')->first()->id,
            ],
            [
                'name' => 'Gel antibacterial',
                'description' => 'Gel desinfectante para manos.',
                'price' => 5000,
                'stock' => 140,
                'code' => 'GELANTIB',
                'image' => null,
                'category_id' => Category::where('name', 'Higiene')->first()->id,
                'provider_id' => Provider::where('name', 'Laboratorios Genéricos S.A.S.')->first()->id,
            ],
        ];

        Product::insert($products);
    }
}